In [1]:
import sys
sys.path.append("../src")

from datacleaning import *

In [2]:
import os
os.getcwd()

'c:\\Users\\laura\\Desktop\\ML II\\ml_project\\notebooks'

#IDS SALTAM NUMERO A FRENTE, O QUE FAZER , manter a numeracao que ja vem_

DETETAR OUTLIERS COM DBSCAN

In [3]:
#perceber bem o que é sobre o dataset

#IDS SALTAM NUMERO A FRENTE, O QUE FAZER , manter a numeracao que ja vem? ok, nao fazer isto pq tira a ligacao dos dois datasets ver istooooo

#ver as birthdates, maybe dar match das datas com o msc e bsc?

#OUTLIERS COM DBSCAN

#meter loyalty number binario

#adicionar validation rules talvez? ou explicar pelo menos???????

#tirar o bsc e o msc e criar uma coluna com isso


# requirements.txt ???''''' ver

#ver se ha impossible values

In [ ]:
dataset = pd.read_csv(r'../data/customer_info.csv',index_col=0)

FileNotFoundError: [Errno 2] No such file or directory: 'data/customer_info.csv'

In [6]:
dataset.head()

NameError: name 'dataset' is not defined

### **Handling Data Types**

### **Handling Missing Values**

In [4]:
dataset.isnull().sum()

customer_id                                    0
customer_name                                  0
customer_gender                                0
customer_birthdate                           165
kids_home                                    330
teens_home                                   330
number_complaints                            661
distinct_stores_visited                      330
lifetime_spend_groceries                       0
lifetime_spend_electronics                   661
typical_hour                                 661
lifetime_spend_vegetables                    661
lifetime_spend_nonalcohol_drinks               0
lifetime_spend_alcohol_drinks                330
lifetime_spend_meat                          661
lifetime_spend_fish                          991
lifetime_spend_hygiene                       330
lifetime_spend_videogames                    661
lifetime_spend_petfood                       661
lifetime_total_distinct_products               0
percentage_of_products_bought_promotion      330
year_first_transaction                         0
loyalty_card_number                        13106
latitude                                       0
longitude                                      0
dtype: int64

In [10]:
dataset[dataset['customer_birthdate'].isnull()]

,customer_name,customer_gender,customer_birthdate,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,lifetime_spend_electronics,typical_hour,...,lifetime_spend_fish,lifetime_spend_hygiene,lifetime_spend_videogames,lifetime_spend_petfood,lifetime_total_distinct_products,percentage_of_products_bought_promotion,year_first_transaction,loyalty_card_number,latitude,longitude
customer_id,,,,,,,,,,,,,,,,,,,,,
401,Msc. Robert Zamora,male,NaN,NaN,0.0,1.0,5.0,1296.0,2377.0,15.0,...,514.0,233.0,319.0,17.0,351.0,0.542064,2016.0,1.0,38.763894,-9.197282
473,Bsc. Nikki Ali,female,NaN,6.0,4.0,1.0,4.0,9805.0,8372.0,11.0,...,1115.0,902.0,350.0,419.0,327.0,0.171643,2029.0,1.0,38.724110,-9.166377
526,Bsc. Theodore Hernandez,male,NaN,1.0,1.0,1.0,5.0,3029.0,898.0,16.0,...,1.0,2004.0,215.0,317.0,76.0,0.022600,2017.0,1.0,38.754457,-9.154369
580,Phd. Steve Ligon,male,NaN,2.0,1.0,3.0,5.0,41315.0,6651.0,12.0,...,1180.0,1188.0,325.0,231.0,248.0,0.151446,2012.0,1.0,38.720267,-9.117971
863,Phd. Sergio Johnson,male,NaN,0.0,1.0,0.0,3.0,16163.0,413.0,15.0,...,70.0,1738.0,194.0,212.0,86.0,0.259576,2014.0,1.0,38.735848,-9.153364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39012,Suzanne Harmon,female,NaN,4.0,1.0,1.0,1.0,21153.0,6179.0,12.0,...,300.0,996.0,400.0,415.0,285.0,0.107332,2005.0,NaN,38.746545,-9.142421
39413,Thomas Bowman,male,NaN,1.0,1.0,0.0,3.0,1042.0,2286.0,8.0,...,24.0,391.0,231.0,98.0,59.0,0.093210,2020.0,NaN,38.734696,-9.119887
39595,Bettye Murphy,female,NaN,1.0,2.0,1.0,1.0,20234.0,280.0,8.0,...,380.0,864.0,110.0,290.0,124.0,-0.022088,2012.0,NaN,38.766244,-9.159973
39857,Donald Wylie,male,NaN,0.0,0.0,1.0,5.0,10790.0,43.0,17.0,...,300.0,308.0,NaN,260.0,22.0,0.017567,2029.0,NaN,38.750542,-9.151325
39881,Chet Burns,male,NaN,0.0,0.0,0.0,2.0,11486.0,229.0,23.0,...,900.0,34.0,185.0,170.0,15.0,-0.318683,2029.0,NaN,38.734491,-9.158304

In [13]:
#mostra me a mediana das datas de nascimento
dataset['customer_birthdate'].median()

TypeError: Cannot convert ['02/12/1970 01:36 PM' '11/13/1975 06:58 PM' '09/10/1971 10:07 AM' ...
 '05/15/1945 11:09 PM' '05/25/1951 09:02 PM' '07/09/1990 10:27 AM'] to numeric

In [5]:
dataset.shape

(33038, 25)

In [4]:

dataset[dataset.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, customer_gender, customer_birthdate, kids_home, teens_home, number_complaints, distinct_stores_visited, lifetime_spend_groceries, lifetime_spend_electronics, typical_hour, lifetime_spend_vegetables, lifetime_spend_nonalcohol_drinks, lifetime_spend_alcohol_drinks, lifetime_spend_meat, lifetime_spend_fish, lifetime_spend_hygiene, lifetime_spend_videogames, lifetime_spend_petfood, lifetime_total_distinct_products, percentage_of_products_bought_promotion, year_first_transaction, loyalty_card_number, latitude, longitude]
Index: []

[0 rows x 25 columns]

In [ ]:
dataset['loyalty_card_number'].value_counts() #meter binario feature engineering

loyalty_card_number
1.0    19932
Name: count, dtype: int64